[features]
seeds = false
[programs.localnet]
decentralized_twitter = "9jUAGyxxVL4D3bJptUwLdtoEwKMZ2xUt1pGSp8ihLtQT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ashishshrestha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
